services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
      AUDIT: "true"
      MAINNET_BLOCK_AUDIT_START_HEIGHT: "840000"
      LIGHTNING: "true"
        #image: mempool/frontend:latest
    image: frontend:local
    user: "1000:1000"
    restart: unless-stopped
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 8383:8080
    networks:
      - main
  api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      MEMPOOL_AUDIT: "true"
      MEMPOOL_BLOCKS_SUMMARIES_INDEXING: "true"
      MEMPOOL_GOGGLES_INDEXING: "true"
      MEMPOOL_RUST_GBT: "true"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "50001"
      ELECTRUM_TLS_ENABLED: "false"
      CORE_RPC_HOST: "bitcoind"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "homecomp"
      CORE_RPC_PASSWORD: "OmZxSTYRrXogU3L0-rgajuqqMzcnAVeyO-6-8w6Njws"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
      LIGHTNING_ENABLED: "true"
      LIGHTNING_BACKEND: "lnd"
      LND_REST_API_URL: "https://lnd:8080"
      LND_TLS_CERT_PATH: "/lnd/tls.cert"
      LND_MACAROON_PATH: "/lnd/readonly.macaroon"
      LIGHTNING_STATS_REFRESH_INTERVAL: 600
      LIGHTNING_GRAPH_REFRESH_INTERVAL: 600
      LIGHTNING_LOGGER_UPDATE_INTERVAL: 30

        #image: mempool/backend:latest
    image: backend:local
    user: "1000:1000"
    restart: unless-stopped
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
      - /home/user/bitcoin/lnd/data/tls.cert:/lnd/tls.cert:ro
      - /home/user/bitcoin/lnd/data/data/chain/bitcoin/mainnet/readonly.macaroon:/lnd/readonly.macaroon:ro
    networks:
      - main
      - bitcoin_main

  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.21
    user: "1000:1000"
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - main

networks:
  main:
  bitcoin_main:
    external: true
